domains:
- domain: demo.wallfair.io
  type: PRIMARY
name: production-frontend
region: fra
services:
- envs:
  - key: REACT_APP_NEWS_API_KEY
    scope: RUN_TIME
    value: $REACT_APP_NEWS_API_KEY
  - key: REACT_APP_BACKEND_URL
    scope: RUN_TIME
    value: $REACT_APP_BACKEND_URL
  - key: REACT_APP_CRASH_GAME_BACKEND_URL
    scope: RUN_TIME
    value: $REACT_APP_CRASH_GAME_BACKEND_URL
  - key: REACT_APP_NEWS_API_SSL_MODE
    scope: RUN_TIME
    value: "true"
  http_port: 80
  image:
    registry_type: DOCR
    repository: frontend
    tag: $VERSION
  instance_count: 1
  instance_size_slug: professional-s
  name: prod-frontend
  routes:
  - path: /
  source_dir: /