domains:
- domain: demo.wallfair.io
  type: PRIMARY
name: production-frontend
region: fra
services:
- http_port: 80
  image:
    registry_type: DOCR
    repository: frontend
    tag: $VERSION
  instance_count: 1
  instance_size_slug: professional-s
  name: prod-frontend
  routes:
  - path: /
  source_dir: /