apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: staging
data:
  REACT_APP_NEWS_API_KEY: dcc5a2750201e19f396c43f98d1d07f0
  REACT_APP_CRASH_GAME_BACKEND_URL: crash-game-backend-k8s.wallfair.io
  REACT_APP_BACKEND_URL: http://backend-k8s.wallfair.io
  REACT_APP_NEWS_API_SSL_MODE: "true"
