apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: elon
commonLabels:
  environment: elon


configMapGenerator:
  - name: frontend-config
    behavior: merge
    envs:
      - environment
    
patches:
  - ingressPatch.yaml