apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-dev-deploy.yaml

namespace: staging
commonLabels:
  environment: staging

configMapGenerator:
  - name: frontend-dev-config
    envs:
      - environment
