apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application
- podDisruptionBudget.yaml

namespace: production
commonLabels:
  environment: production

configMapGenerator:
- behavior: merge
  envs:
  - environment
  name: frontend-config

patches:
- ingressPatch.yaml
- replicasPatch.yaml
- resourcesPatch.yaml
- prodConfigPatch.yaml
- priorityPatch.yaml
