apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: production
commonLabels:
  environment: production

configMapGenerator:
- behavior: merge
  envs:
  - environment
  name: frontend-config

patchesStrategicMerge:
- ingressPatch.yaml
- replicasPatch.yaml
- resourcesPatch.yaml
