apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../application

namespace: production
commonLabels:
  environment: production

configMapGenerator:
  - name: frontend-config
    behavior: merge
    envs:
      - environment
