apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: production
commonLabels:
  environment: production

configMapGenerator:
- behavior: merge
  envs:
  - environment
  name: frontend-config

patches:
- ingressPatch.yaml
- replicasPatch.yaml
- resourcesPatch.yaml

images:
- name: registry.digitalocean.com/wallfair/frontend_k8s
  newTag: delete
