apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
spec:
  secretName: frontend-cert-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - alpa.casino
