apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  tls:
  - hosts:
    - alpa.casino
    secretName: frontend-cert-secret
  rules:
  - host: alpa.casino
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-main
              port:
                number: 80
