apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application
- podDisruptionBudget.yaml
- certificate.yaml
#- geoblockOverride.yaml

namespace: alpa-prod
commonLabels:
  environment: alpa-prod

configMapGenerator:
- behavior: merge
  envs:
  - environment
  name: frontend-config

patches:
- replicasPatch.yaml
- resourcesPatch.yaml
- prodConfigPatch.yaml
- priorityPatch.yaml
