apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: staging
data:
  REACT_APP_CRASH_GAME_BACKEND_URL: https://staging-elon-api.wallfair.io/
  REACT_APP_BACKEND_URL: https://staging-api.wallfair.io/
  REACT_APP_NEWS_API_SSL_MODE: "true"
