name: Deploy to Kubernetes cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - production

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image (staging)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build . -q --build-arg REACT_APP_CRASH_GAME_BACKEND_URL="https://staging-elon-api.wallfair.io/" --build-arg REACT_APP_BACKEND_URL="https://staging-api.wallfair.io/" --build-arg REACT_APP_NEWS_API_KEY=${{ secrets.REACT_APP_NEWS_API_KEY }} --build-arg REACT_APP_RECAPTCHA_KEY=${{ secrets.REACT_APP_RECAPTCHA_KEY }} --build-arg REACT_APP_GTM_ID=${{ secrets.REACT_APP_GTM_ID }}  -t registry.digitalocean.com/wallfair/frontend_k8s_staging:${GITHUB_SHA::6}
          docker push registry.digitalocean.com/wallfair/frontend_k8s_staging:${GITHUB_SHA::6}
      - name: Build the docker image (staging)
        if: github.ref == 'refs/heads/production'
        run: |
          docker build . -q --build-arg REACT_APP_CRASH_GAME_BACKEND_URL="https://production-elon-api.wallfair.io/" --build-arg REACT_APP_BACKEND_URL="https://production-api.wallfair.io/" --build-arg REACT_APP_NEWS_API_KEY=${{ secrets.REACT_APP_NEWS_API_KEY }} --build-arg REACT_APP_RECAPTCHA_KEY=${{ secrets.REACT_APP_RECAPTCHA_KEY }} --build-arg REACT_APP_GTM_ID=${{ secrets.REACT_APP_GTM_ID }}  -t registry.digitalocean.com/wallfair/frontend_k8s_prod:${GITHUB_SHA::6}
          docker push registry.digitalocean.com/wallfair/frontend_k8s_prod:${GITHUB_SHA::6}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Edit deployment image (staging)
        if: github.ref == 'refs/heads/main'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/staging
            kustomize edit set image registry.digitalocean.com/wallfair/frontend_k8s=registry.digitalocean.com/wallfair/frontend_k8s_staging:${GITHUB_SHA::6}
            kustomize build .
      - name: Edit deployment image (production)
        if: github.ref == 'refs/heads/production'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/production
            kustomize edit set image registry.digitalocean.com/wallfair/frontend_k8s=registry.digitalocean.com/wallfair/frontend_k8s_prod:${GITHUB_SHA::6}
            kustomize build .
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/main'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/staging
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/production
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/production
      
  
